"""initial schema

Revision ID: a632fdaa503c
Revises:
Create Date: 2026-09-28 22:52:42.945779

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a632fdaa503c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "icp_profiles",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=16), server_default="sales", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "rules", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('sales', 'acquisition')", name=op.f("ck_icp_profiles_mode")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_icp_profiles")),
    )
    op.create_table(
        "import_jobs",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("total_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicates_removed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')",
            name=op.f("ck_import_jobs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("revenue_estimate", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("copyright_year", sa.Integer(), nullable=True),
        sa.Column(
            "tech_stack",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "socials", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "signals", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("website_status", sa.String(length=16), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("grade", sa.String(length=1), nullable=True),
        sa.Column(
            "score_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=16), server_default="new", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), server_default="csv", nullable=False),
        sa.Column("import_job_id", sa.UUID(), nullable=True),
        sa.Column("last_enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("grade IN ('A', 'B', 'C', 'D')", name=op.f("ck_companies_grade")),
        sa.CheckConstraint(
            "stage IN ('new', 'qualified', 'contacted', 'disqualified')",
            name=op.f("ck_companies_stage"),
        ),
        sa.CheckConstraint(
            "website_status IN ('alive', 'dead', 'blocked', 'timeout')",
            name=op.f("ck_companies_website_status"),
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name=op.f("ck_companies_score_range")),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_companies_import_job_id_import_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("domain", name=op.f("uq_companies_domain")),
    )
    op.create_index(
        "ix_companies_country_industry", "companies", ["country", "industry"], unique=False
    )
    op.create_index("ix_companies_import_job_id", "companies", ["import_job_id"], unique=False)
    op.create_index(
        op.f("ix_companies_name_normalized"), "companies", ["name_normalized"], unique=False
    )
    op.create_index(
        "ix_companies_score", "companies", [sa.literal_column("score DESC")], unique=False
    )
    op.create_index("ix_companies_stage", "companies", ["stage"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("email_status", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("email_type", sa.String(length=16), nullable=True),
        sa.Column("phone_e164", sa.String(length=32), nullable=True),
        sa.Column("phone_valid", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("is_decision_maker", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("source", sa.String(length=16), server_default="csv", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email_status IN ('valid_mx', 'no_mx', 'invalid_syntax', 'disposable', 'unknown')",
            name=op.f("ck_contacts_email_status"),
        ),
        sa.CheckConstraint(
            "email_type IN ('personal', 'role')", name=op.f("ck_contacts_email_type")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("company_id", "email", name="uq_contacts_company_email"),
    )
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    # ### end Alembic commands ###

    # full-text search over name + description (autogenerate can't do expression gin indexes)
    op.execute(
        "CREATE INDEX ix_companies_search ON companies "
        "USING gin (to_tsvector('simple', name || ' ' || coalesce(description, '')))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_companies_search")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index("ix_companies_stage", table_name="companies")
    op.drop_index("ix_companies_score", table_name="companies")
    op.drop_index(op.f("ix_companies_name_normalized"), table_name="companies")
    op.drop_index("ix_companies_import_job_id", table_name="companies")
    op.drop_index("ix_companies_country_industry", table_name="companies")
    op.drop_table("companies")
    op.drop_table("import_jobs")
    op.drop_table("icp_profiles")
    # ### end Alembic commands ###
