"""tune lead list indexes

The old score index was DESC NULLS FIRST, but the leads list sorts
DESC NULLS LAST, id - so postgres ignored it and sorted the whole table.
With 5k rows: default page went from a full sort (~1.7ms) to an index
scan (~0.3ms), and the "verified email" filter now uses an index-only scan.

Revision ID: a33e442121cd
Revises: a632fdaa503c
Create Date: 2026-09-29 12:45:30.934904

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a33e442121cd"
down_revision: str | Sequence[str] | None = "a632fdaa503c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_score"), table_name="companies")
    op.create_index(
        "ix_companies_score_id",
        "companies",
        [sa.literal_column("score DESC NULLS LAST"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_contacts_company_status", "contacts", ["company_id", "email_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contacts_company_status", table_name="contacts")
    op.drop_index("ix_companies_score_id", table_name="companies")
    op.create_index(
        op.f("ix_companies_score"), "companies", [sa.literal_column("score DESC")], unique=False
    )
    # ### end Alembic commands ###
